version: '3'
services:
        web:
                image: dolphins_v1
                build: .
                ports:
                        - "8090:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped